In [12]:
print(4)
print("Heyy")

4
Heyy


In [21]:
"Hello"
"Hi"

'Hi'

In [22]:
"Hello","Hi"

('Hello', 'Hi')

In [18]:
4
"Heyy"

'Heyy'

In [23]:
#str
#int
#float

In [31]:
a1= 4
a2= 5.6
a3= 'Hello'
a4= 'b'
a5= "Heyy"
a6= "I'm learning AI"

In [32]:
type(a7)

str

In [33]:
#comment
#this is also a comment
print(a1) #coment here

4


In [34]:
a=input("Enter your name: ")

Enter your name: JOhn


In [36]:
#create a simple calculator
#take 2 numbers from the user, 
#perform addition and multiplication and display the results

In [37]:
num1=int(input("Enter 1st number: "))
num2=int(input("Enter 2nd number: "))
sum=num1+num2
prod=num1*num2
print("Sum of",num1,"and",num2,"is",sum)
print("Product of",num1,"and",num2,"is",prod)

Enter 1st number: 3
Enter 2nd number: 5
Sum of  3 and 5 is 8
Product of  3 and 5 is 15


In [38]:
#strings

In [39]:
x="Hi there, I'm using WhatsApp"

In [40]:
len(x)

28

In [47]:
x[-3]

'A'

In [48]:
x[0:3]  #inclusve, exclusive

'Hi '

In [50]:
x[0:5]

'Hi th'

In [51]:
x[:5]

'Hi th'

In [52]:
x[12:]

'm using WhatsApp'

In [53]:
x[:]

"Hi there, I'm using WhatsApp"

In [56]:
x=x.lower()

In [57]:
x

"hi there, i'm using whatsapp"

In [58]:
x

"hi there, i'm using whatsapp"

In [60]:
x.split('i')

['h', ' there, ', "'m us", 'ng whatsapp']

In [61]:
a2="myname@gmail.com"
a2.split("@")

['myname', 'gmail.com']

In [ ]:
#conditional statements
#if
#if else
#elif ladder
#nested if

In [62]:
#write a code to determine the grade of students scoring betwn 0 and 100
#90 and above is excellent
#70 and 90 is good
#50 and 70 is average
#below 50 is needs improvement

In [ ]:
marks= int(input("Enter the marks scored in whole numbers(0-100): "))
if(marks>100):
  print("Invalid marks, please rerun the cell and try again")
elif(marks>=90):
  print("Excellent")
elif(marks>=70):
  print("Good")
elif(marks>=50):
  print("average")
elif(marks>0):
  print("Needs improvement")
else:
  print("Invalid marks, please rerun the cell and try again")

In [79]:
#Use nested if, else conditions to find the greatest of 3 numbers
#use input statements to get the numbers

In [84]:
num1=int(input("Enter the first number: "))
num2=int(input("Enter the second number: "))
num3=int(input("Enter the third number: "))
if(num1<num2):
  if(num2<num3):
    print("Number 3 is the greatest")
  else:
    print("Number 2 is the greatest")
else:
  if(num1>num3):
    print("Number 1 is the greatest")
  else:
    print("Number 3 is the greatest")

Enter the first number: 5
Enter the second number: 15
Enter the third number: 10
Number 2 is the greatest


In [85]:
#Tuples, Lists, Dictionaries

In [86]:
#Tuples- immutable, ()
#Lists - mutable, []
#Dictionary - key value pair,  {}


In [87]:
tup1=(1,4,6,3,2,5)

In [90]:
tup1

(1, 4, 6, 3, 2, 5)

In [88]:
type(tup1)

tuple

In [89]:
tup1[0]

1

In [92]:
tup1[2]

6

In [93]:
tup1[-1]

5

In [94]:
tup1[:3]

(1, 4, 6)

In [95]:
tup2=(5,"Heyy",3.2,4,"H")

In [96]:
tup2[1]

'Heyy'

In [97]:
tup2[1]="Hello"

TypeError: ignored

In [98]:
tup3=(2,5,("Heyy",4),"Hi",3.2)

In [99]:
len(tup3)

5

In [100]:
tup3[1]

5

In [102]:
tup3[2]

('Heyy', 4)

In [101]:
tup3[2][1]

4

In [103]:
tup2

(5, 'Heyy', 3.2, 4, 'H')

In [104]:
tup2*3

(5, 'Heyy', 3.2, 4, 'H', 5, 'Heyy', 3.2, 4, 'H', 5, 'Heyy', 3.2, 4, 'H')

In [105]:
tup2

(5, 'Heyy', 3.2, 4, 'H')

In [106]:
tup2+tup1

(5, 'Heyy', 3.2, 4, 'H', 1, 4, 6, 3, 2, 5)

In [107]:
s1="Hello"
s2="Hi"
s1+s2

'HelloHi'

In [108]:
#Lists

In [109]:
list1= [1,3,4,7,5,2]

In [110]:
type(list1)

list

In [111]:
list1[0]

1

In [112]:
list1[-1]

2

In [113]:
list1[3:]

[7, 5, 2]

In [114]:
lst=[1,2,3,4,5,6]

In [115]:
lst[3]

4

In [116]:
lst[3]=40
lst

[1, 2, 3, 40, 5, 6]

In [117]:
#Lists have many functions

In [118]:
lst.index(40)

3

In [119]:
lst.remove(5)  #used to remove the specified element from the list
lst

[1, 2, 3, 40, 6]

In [122]:
lst.remove(5)

ValueError: ignored

In [120]:
lst.pop(2)

3

In [121]:
lst

[1, 2, 40, 6]

In [123]:
lst.pop(6)  #removes the element from the specified index

IndexError: ignored

In [125]:
lst.insert(3,30)  #used to insert the element at specified index
lst

[1, 2, 40, 30, 6]

In [128]:
lst.append(8)   #used to add the element at the end of the list
lst

[1, 2, 40, 30, 6, 8, 8, 8]

In [129]:
lst.extend(list1)

In [130]:
lst

[1, 2, 40, 30, 6, 8, 8, 8, 1, 3, 4, 7, 5, 2]

In [131]:
lst+list1

[1, 2, 40, 30, 6, 8, 8, 8, 1, 3, 4, 7, 5, 2, 1, 3, 4, 7, 5, 2]

In [132]:
lst

[1, 2, 40, 30, 6, 8, 8, 8, 1, 3, 4, 7, 5, 2]

In [133]:
lst.sort()

In [134]:
lst

[1, 1, 2, 2, 3, 4, 5, 6, 7, 8, 8, 8, 30, 40]

In [135]:
lst.reverse()
lst

[40, 30, 8, 8, 8, 7, 6, 5, 4, 3, 2, 2, 1, 1]

In [136]:
lst.clear()
lst

[]

In [139]:
a=True
type(a)

bool

In [140]:
#Dictionaries

In [141]:
#Dictionary is technically not a sequence, it is a key value pair data structure

In [142]:
d= {'John':6,'Jack':8,'Juliet':5,'Jacob':4 }

In [143]:
d

{'Jack': 8, 'Jacob': 4, 'John': 6, 'Juliet': 5}

In [144]:
type(d)

dict

In [145]:
len(d)

4

In [146]:
d.keys()

dict_keys(['John', 'Jack', 'Juliet', 'Jacob'])

In [147]:
d.values()

dict_values([6, 8, 5, 4])

In [149]:
d.items()

dict_items([('John', 6), ('Jack', 8), ('Juliet', 5), ('Jacob', 4)])

In [150]:
[('John', 6), ('Jack', 8), ('Juliet', 5), ('Jacob', 4)]

[('John', 6), ('Jack', 8), ('Juliet', 5), ('Jacob', 4)]

In [151]:
d

{'Jack': 8, 'Jacob': 4, 'John': 6, 'Juliet': 5}

In [152]:
d['Jacob']

4

In [153]:
d.get('Jacob')

4

In [154]:
d.popitem()

('Jacob', 4)

In [155]:
keys=['A','B','C','D']
def_value=98

In [156]:
d1=dict.fromkeys(keys,def_value)
d1

{'A': 98, 'B': 98, 'C': 98, 'D': 98}

In [157]:
d1.clear()
d1

{}

In [158]:
#loops
#for
#while
#nested loops

In [159]:
#while
#starting point, 
#ending point, or condition
#step or an iteration

In [1]:
a=0
while(a<10):
  print(a)
  a=a+1

0
1
2
3
4
5
6
7
8
9


In [2]:
a=3
while(a<20):
  print(a)
  a=a+4

3
7
11
15
19


In [3]:
i=3
while(i<31):
  print(i)
  i=i+3

3
6
9
12
15
18
21
24
27
30


In [4]:
i=10
while(i>0):
  i=i-2
  print(i)

8
6
4
2
0


In [5]:
#to get the incremental sum of numbers from 0 to 10

In [7]:
num=0
sum=0
while(num<=10):
  sum=sum+num
  print(sum)
  num=num+1
print("Final sum",sum)


0
1
3
6
10
15
21
28
36
45
55
Final sum 55


In [8]:
num=0
sum=0
while(num<=10):
  sum=sum+num
  print("number=",num,"sum=",sum)
  num=num+1
print("Final sum",sum)

number= 0 sum= 0
number= 1 sum= 1
number= 2 sum= 3
number= 3 sum= 6
number= 4 sum= 10
number= 5 sum= 15
number= 6 sum= 21
number= 7 sum= 28
number= 8 sum= 36
number= 9 sum= 45
number= 10 sum= 55
Final sum 55


In [9]:
#for loop

In [ ]:
a=0
while(a<10):
  print(a)
  a=a+1

In [11]:
for a in range(0,10,1):
  print(a)

0
1
2
3
4
5
6
7
8
9


In [12]:
for a in range(0,10):
  print(a)

0
1
2
3
4
5
6
7
8
9


In [13]:
for a in range(10):
  print(a)

0
1
2
3
4
5
6
7
8
9


In [16]:
for i in range(3,15,2):
  print(i)

3
5
7
9
11
13


In [24]:
for i in range(3,15,2):
  print(i)

3
5
7
9
11
13


In [20]:
list1=[1,5,4,38,4,6,2]
for i in list1:
  print(i,end=" ")

1 5 4 38 4 6 2 

In [21]:
for i in [1,5,4,38,4,6,2]:
  print(i,end=" ")

1 5 4 38 4 6 2 

In [25]:
#*
#**
#***
#****
#*****

In [27]:
for i in range(1,6,1):
  print("*"*i)

*
**
***
****
*****


In [29]:
n=5
for i in range(1,n+1,1):
  for k in range(1,i+1,1):
    print("*",end="")
  print()

*
**
***
****
*****


In [30]:
#functions

In [31]:
#builtin functions
#user defined
#object methods

In [34]:
def myfnc(a,b):
  print(a,b)
  

In [35]:
myfnc(1,2)

1 2


In [36]:
myfnc(1,2)
myfnc("Heyy",2)
myfnc(1,"Hello")
myfnc("heyy","Hi")

1 2
Heyy 2
1 Hello
heyy Hi


In [1]:
#Function with a return statement
def fun1(x,y):
  sum=x+y
  return sum

In [2]:
c=fun1(3,4)
c

7

In [3]:
def fun1(x,y=5):
  sum=x+y
  return sum

In [5]:
c=fun1(3)
c

8

In [6]:
#Libraries

In [7]:
#time

In [8]:
for a in range(0,10,1):
  print(a)

0
1
2
3
4
5
6
7
8
9


In [ ]:
import time
for a in range(0,10,1):
  print(a)
  time.sleep(0.5)

In [ ]:
import time as ti
for a in range(0,10,1):
  print(a)
  ti.sleep(0.5)

In [ ]:
from time import sleep
for a in range(0,10,1):
  print(a)
  sleep(0.5)

In [ ]:
from time import sleep as sl
for a in range(0,10,1):
  print(a)
  sl(0.5)

In [15]:
#numpy  #numerical calculations
#matplotlib  #data visualization
#pandas  # data analysis
#sci-kit learn   #ML algorithms and metrics

In [16]:
#NumPy : Numerical Python
#arrays

In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [21]:
a=np.array([1,3,4,7,5])

In [22]:
a

array([1, 3, 4, 7, 5])

In [23]:
type(a)

numpy.ndarray

In [24]:
b=np.array([4,5,6,5,4])
b

array([4, 5, 6, 5, 4])

In [30]:
b.ndim

1

In [25]:
b[0]

4

In [26]:
b[-1]

4

In [27]:
b[2:4]

array([6, 5])

In [28]:
c=np.array([[1,2],[3,4]])
c


array([[1, 2],
       [3, 4]])

In [45]:
c.shape

(2, 2)

In [29]:
c.ndim

2

In [33]:
d=np.array([[[1]],[[2]],[[3]]])
d

array([[[1]],

       [[2]],

       [[3]]])

In [44]:
d.shape

(3, 1, 1)

In [46]:
d.ndim

3

In [36]:
arr1=np.array([1,2,3,4,5],ndmin=2)

In [37]:
arr1

array([[1, 2, 3, 4, 5]])

In [38]:
arr1.ndim

2

In [39]:
arr1.shape

(1, 5)

In [40]:
c

array([[1, 2],
       [3, 4]])

In [41]:
c.shape

(2, 2)

In [42]:
c.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [43]:
#create an array of shape 3,4.
#then use the reshape function to reshape the array to 4,3 and 6,2

In [47]:
arr2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [48]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [49]:
arr2.shape

(3, 4)

In [50]:
arr2.ndim

2

In [51]:
arr2.size

12

In [52]:
arr2.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [53]:
arr2.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [54]:
arr2.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [55]:
arr2.reshape(2,5)

ValueError: ignored

In [56]:
arr2.reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [57]:
arr2.reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [64]:
np.random.seed(95)
np.random.randint(0,15,5)

array([ 6,  9,  3,  6, 14])