In [3]:
#numpy random method
import numpy as np

In [7]:
np.random.seed(0)
a=np.random.randint(0,50,10)
a

array([44, 47,  0,  3,  3, 39,  9, 19, 21, 36])

In [8]:
#OTP

In [12]:
np.random.randint(0,9,6)

array([2, 3, 8, 1, 3, 3])

In [14]:
#create an array of 25 random numbers between 0 and 20
#apply the seed value of 13

In [15]:
np.random.seed(13)
a=np.random.randint(0,20,25)
a

array([18, 16, 10, 16,  6,  2, 12,  3,  2, 14,  5, 13, 10,  9, 11,  2,  0,
       19, 19, 11, 11,  1, 18, 11,  8])

In [16]:
a=np.sort(a)
a

array([ 0,  1,  2,  2,  2,  3,  5,  6,  8,  9, 10, 10, 11, 11, 11, 11, 12,
       13, 14, 16, 16, 18, 18, 19, 19])

In [19]:
b=np.unique(a)

In [18]:
np.unique(a,return_counts=True)

(array([ 0,  1,  2,  3,  5,  6,  8,  9, 10, 11, 12, 13, 14, 16, 18, 19]),
 array([1, 1, 3, 1, 1, 1, 1, 1, 2, 4, 1, 1, 1, 2, 2, 2]))

In [20]:
b

array([ 0,  1,  2,  3,  5,  6,  8,  9, 10, 11, 12, 13, 14, 16, 18, 19])

In [21]:
c=np.append(b,5)
c

array([ 0,  1,  2,  3,  5,  6,  8,  9, 10, 11, 12, 13, 14, 16, 18, 19,  5])

In [22]:
d=np.power(c,2)
d

array([  0,   1,   4,   9,  25,  36,  64,  81, 100, 121, 144, 169, 196,
       256, 324, 361,  25])

In [23]:
e=np.power(c,3)
e

array([   0,    1,    8,   27,  125,  216,  512,  729, 1000, 1331, 1728,
       2197, 2744, 4096, 5832, 6859,  125])

In [24]:
f=np.sqrt(d)
f

array([ 0.,  1.,  2.,  3.,  5.,  6.,  8.,  9., 10., 11., 12., 13., 14.,
       16., 18., 19.,  5.])

In [25]:
np.ones(2)

array([1., 1.])

In [26]:
np.zeros(2)

array([0., 0.])

In [27]:
np.ones(2,dtype=np.int16)

array([1, 1], dtype=int16)

In [28]:
np.ones([2,2],dtype=np.int16)

array([[1, 1],
       [1, 1]], dtype=int16)

In [29]:
np.ones([3,2],dtype=np.int16)

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int16)

In [30]:
a

array([ 0,  1,  2,  2,  2,  3,  5,  6,  8,  9, 10, 10, 11, 11, 11, 11, 12,
       13, 14, 16, 16, 18, 18, 19, 19])

In [31]:
a.sum()

247

In [32]:
a.min()

0

In [33]:
a.max()

19

In [34]:
a.mean()

9.88

In [35]:
#np.arange and np.linspace

In [36]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.arange(3,30,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [40]:
np.arange(1,26,4)
#1,5,9,13,17,21,25

array([ 1,  5,  9, 13, 17, 21, 25])

In [41]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [42]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [43]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [47]:
a1=np.arange(9,dtype=np.float).reshape(3,3)
a1

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [48]:
b1=np.array([10,9,8])

In [49]:
np.add(a1,b1)

array([[10., 10., 10.],
       [13., 13., 13.],
       [16., 16., 16.]])

In [50]:
np.subtract(a1,b1)

array([[-10.,  -8.,  -6.],
       [ -7.,  -5.,  -3.],
       [ -4.,  -2.,   0.]])

In [51]:
np.multiply(a1,b1)

array([[ 0.,  9., 16.],
       [30., 36., 40.],
       [60., 63., 64.]])

In [54]:
g=np.divide(a1,b1)
g

array([[0.        , 0.11111111, 0.25      ],
       [0.3       , 0.44444444, 0.625     ],
       [0.6       , 0.77777778, 1.        ]])

In [55]:
np.reciprocal(g)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in reciprocal
  """Entry point for launching an IPython kernel.


array([[       inf, 9.        , 4.        ],
       [3.33333333, 2.25      , 1.6       ],
       [1.66666667, 1.28571429, 1.        ]])