In [1]:
#Pandas
#It is used for data analysis

In [2]:
#Series  and DataFrames
#Series- 1D (column)
#Dataframe - 2D structure that can be thought of as a spreadsheet  (rows*columns)
#dataframe could also be understood as combination of multiple series

In [3]:
#Series: it is similar to a numpy array, but a few differences
#Series could have a customized labeled index
#if any values are missing in numpy, it will not detect them
#but in series, it will represented as NaN(Not a Number)

In [4]:
import numpy as np
import pandas as pd

In [5]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [6]:
a[0]

1

In [7]:
s=pd.Series(a)
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [8]:
type(s)

pandas.core.series.Series

In [9]:
s[4]

5

In [10]:
#creating a series using fancy labeling

In [11]:
list1=[10,30,23,45,67]
labels=['v','w','x','y','z']

In [12]:
s1=pd.Series(data=list1,index=labels)
s1

v    10
w    30
x    23
y    45
z    67
dtype: int64

In [13]:
#create a series using a numpy array, use np.arange() to create an array
#use a fancy index. the index should contains a list of names of yuor classmates

In [14]:
arr1=np.arange(10,25,3)
arr1

array([10, 13, 16, 19, 22])

In [15]:
names=['John','Jack','Jude','Jones','James']

In [16]:
s2=pd.Series(data=arr1,index=names)
s2

John     10
Jack     13
Jude     16
Jones    19
James    22
dtype: int64

In [17]:
s2['Jude']

16

In [18]:
#dataframes

In [19]:
mydataset= {
    'cars':['BMW','Volvo','Fiat'],
    'values':[3,7,2]    
}

In [20]:
type(mydataset)

dict

In [21]:
pd.DataFrame(mydataset)

cars  values
0    BMW       3
1  Volvo       7
2   Fiat       2

In [22]:
marks=np.random.randint(20,50,(4,4))
marks

array([[33, 41, 34, 43],
       [40, 22, 22, 49],
       [22, 23, 37, 31],
       [39, 31, 44, 28]])

In [23]:
subjects=['Math','Computers','Biology','Sports']
names   =['Peter','Josh',   'Rob',    'John']

In [24]:
df=pd.DataFrame(marks, index=names,columns=subjects)
df

Math  Computers  Biology  Sports
Peter    33         41       34      43
Josh     40         22       22      49
Rob      22         23       37      31
John     39         31       44      28

In [25]:
df['Math']

Peter    33
Josh     40
Rob      22
John     39
Name: Math, dtype: int64

In [26]:
df['Total']=df['Math']+df['Computers']+df['Biology']+df['Sports']
df

Math  Computers  Biology  Sports  Total
Peter    33         41       34      43    151
Josh     40         22       22      49    133
Rob      22         23       37      31    113
John     39         31       44      28    142

In [27]:
df['Percentage']=(df['Total']/200)*100
df

Math  Computers  Biology  Sports  Total  Percentage
Peter    33         41       34      43    151        75.5
Josh     40         22       22      49    133        66.5
Rob      22         23       37      31    113        56.5
John     39         31       44      28    142        71.0

In [28]:
type(df)

pandas.core.frame.DataFrame

In [29]:
df2=df.drop('Percentage',axis=1)  #axis=1 specifies removing the columns
df2

Math  Computers  Biology  Sports  Total
Peter    33         41       34      43    151
Josh     40         22       22      49    133
Rob      22         23       37      31    113
John     39         31       44      28    142

In [30]:
df2=df2.drop('Josh',axis=0)  #axis=0 specifies removing the columns

In [31]:
df2

Math  Computers  Biology  Sports  Total
Peter    33         41       34      43    151
Rob      22         23       37      31    113
John     39         31       44      28    142

In [32]:
#Dataframe with values from a dictionary
#handling missing values

In [48]:
d={'Cricket':[1,3,np.nan,4,6,7,2,np.nan],
   'Baseball':[5,np.nan,np.nan,5,7,4,7,3],
   'Tennis':[1,2,3,4,5,6,7,8]}

In [49]:
df=pd.DataFrame(d)
df

Cricket  Baseball  Tennis
0      1.0       5.0       1
1      3.0       NaN       2
2      NaN       NaN       3
3      4.0       5.0       4
4      6.0       7.0       5
5      7.0       4.0       6
6      2.0       7.0       7
7      NaN       3.0       8

In [50]:
#Handling of missing data
#(1) Drop the rows or colums containing the missing values(dropna)
#(2) Fill the missing values with 0 (fillna)
#(3) Fill the missing values with mean or median or mode (fillna)

In [51]:
df2=df.dropna(axis=0)  #dropping the null values along the rows
df2

Cricket  Baseball  Tennis
0      1.0       5.0       1
3      4.0       5.0       4
4      6.0       7.0       5
5      7.0       4.0       6
6      2.0       7.0       7

In [52]:
df.dropna(axis=1) #dropping the null values along the columns

Tennis
0       1
1       2
2       3
3       4
4       5
5       6
6       7
7       8

In [53]:
df.fillna(value=0)

Cricket  Baseball  Tennis
0      1.0       5.0       1
1      3.0       0.0       2
2      0.0       0.0       3
3      4.0       5.0       4
4      6.0       7.0       5
5      7.0       4.0       6
6      2.0       7.0       7
7      0.0       3.0       8

In [54]:
df['Cricket']=df['Cricket'].fillna(value=df['Cricket'].median())

In [55]:
df

Cricket  Baseball  Tennis
0      1.0       5.0       1
1      3.0       NaN       2
2      3.5       NaN       3
3      4.0       5.0       4
4      6.0       7.0       5
5      7.0       4.0       6
6      2.0       7.0       7
7      3.5       3.0       8

In [56]:
df['Baseball']=df['Baseball'].fillna(value=df['Baseball'].median())
df

Cricket  Baseball  Tennis
0      1.0       5.0       1
1      3.0       5.0       2
2      3.5       5.0       3
3      4.0       5.0       4
4      6.0       7.0       5
5      7.0       4.0       6
6      2.0       7.0       7
7      3.5       3.0       8

In [57]:
df=df.set_index([['Alpha','Bravo','Charlie','Delta','Echo','Foxtrot','Golf','Hotel']])
df

Cricket  Baseball  Tennis
Alpha        1.0       5.0       1
Bravo        3.0       5.0       2
Charlie      3.5       5.0       3
Delta        4.0       5.0       4
Echo         6.0       7.0       5
Foxtrot      7.0       4.0       6
Golf         2.0       7.0       7
Hotel        3.5       3.0       8

In [58]:
df=df.reset_index()
#df.reset_index(inplace=True)
df

index  Cricket  Baseball  Tennis
0    Alpha      1.0       5.0       1
1    Bravo      3.0       5.0       2
2  Charlie      3.5       5.0       3
3    Delta      4.0       5.0       4
4     Echo      6.0       7.0       5
5  Foxtrot      7.0       4.0       6
6     Golf      2.0       7.0       7
7    Hotel      3.5       3.0       8