In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("/content/drive/MyDrive/RNSIT March17/Melbourne_housing_FULL.csv")
df.head()

Suburb             Address  Rooms Type      Price Method SellerG  \
0  Abbotsford       68 Studley St      2    h        NaN     SS  Jellis   
1  Abbotsford        85 Turner St      2    h  1480000.0      S  Biggin   
2  Abbotsford     25 Bloomburg St      2    h  1035000.0      S  Biggin   
3  Abbotsford  18/659 Victoria St      3    u        NaN     VB  Rounds   
4  Abbotsford        5 Charles St      3    h  1465000.0     SP  Biggin   

        Date  Distance  Postcode  ...  Bathroom  Car  Landsize  BuildingArea  \
0  3/09/2016       2.5    3067.0  ...       1.0  1.0     126.0           NaN   
1  3/12/2016       2.5    3067.0  ...       1.0  1.0     202.0           NaN   
2  4/02/2016       2.5    3067.0  ...       1.0  0.0     156.0          79.0   
3  4/02/2016       2.5    3067.0  ...       2.0  1.0       0.0           NaN   
4  4/03/2017       2.5    3067.0  ...       2.0  0.0     134.0         150.0   

   YearBuilt         CouncilArea Lattitude  Longtitude             Regionname  \
0        NaN  Yarra City Council  -37.8014    144.9958  Northern Metropolitan   
1        NaN  Yarra City Council  -37.7996    144.9984  Northern Metropolitan   
2     1900.0  Yarra City Council  -37.8079    144.9934  Northern Metropolitan   
3        NaN  Yarra City Council  -37.8114    145.0116  Northern Metropolitan   
4     1900.0  Yarra City Council  -37.8093    144.9944  Northern Metropolitan   

  Propertycount  
0        4019.0  
1        4019.0  
2        4019.0  
3        4019.0  
4        4019.0  

[5 rows x 21 columns]

In [3]:
df.shape

(34857, 21)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34857 entries, 0 to 34856
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Suburb         34857 non-null  object 
 1   Address        34857 non-null  object 
 2   Rooms          34857 non-null  int64  
 3   Type           34857 non-null  object 
 4   Price          27247 non-null  float64
 5   Method         34857 non-null  object 
 6   SellerG        34857 non-null  object 
 7   Date           34857 non-null  object 
 8   Distance       34856 non-null  float64
 9   Postcode       34856 non-null  float64
 10  Bedroom2       26640 non-null  float64
 11  Bathroom       26631 non-null  float64
 12  Car            26129 non-null  float64
 13  Landsize       23047 non-null  float64
 14  BuildingArea   13742 non-null  float64
 15  YearBuilt      15551 non-null  float64
 16  CouncilArea    34854 non-null  object 
 17  Lattitude      26881 non-null  float64
 18  Longti

In [5]:
df.isnull().sum()

Suburb               0
Address              0
Rooms                0
Type                 0
Price             7610
Method               0
SellerG              0
Date                 0
Distance             1
Postcode             1
Bedroom2          8217
Bathroom          8226
Car               8728
Landsize         11810
BuildingArea     21115
YearBuilt        19306
CouncilArea          3
Lattitude         7976
Longtitude        7976
Regionname           3
Propertycount        3
dtype: int64

In [6]:
#taking columns based on datatype
#numerical and non-numerical columns

In [11]:
df.dtypes  #prints a series depicting datatype for each column

Suburb            object
Address           object
Rooms              int64
Type              object
Price            float64
Method            object
SellerG           object
Date              object
Distance         float64
Postcode         float64
Bedroom2         float64
Bathroom         float64
Car              float64
Landsize         float64
BuildingArea     float64
YearBuilt        float64
CouncilArea       object
Lattitude        float64
Longtitude       float64
Regionname        object
Propertycount    float64
dtype: object

In [18]:
df.dtypes[df.dtypes!='object'] #display datatypes where datatype is not equal to object

Rooms              int64
Price            float64
Distance         float64
Postcode         float64
Bedroom2         float64
Bathroom         float64
Car              float64
Landsize         float64
BuildingArea     float64
YearBuilt        float64
Lattitude        float64
Longtitude       float64
Propertycount    float64
dtype: object

In [16]:
df.dtypes[df.dtypes!='object'].index

Index(['Rooms', 'Price', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'Lattitude', 'Longtitude',
       'Propertycount'],
      dtype='object')

In [19]:
num_col=df.dtypes[df.dtypes!='object'].index.values
num_col

array(['Rooms', 'Price', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom',
       'Car', 'Landsize', 'BuildingArea', 'YearBuilt', 'Lattitude',
       'Longtitude', 'Propertycount'], dtype=object)

In [20]:
cat_col=df.dtypes[df.dtypes=='object'].index.values
cat_col

array(['Suburb', 'Address', 'Type', 'Method', 'SellerG', 'Date',
       'CouncilArea', 'Regionname'], dtype=object)

In [22]:
#curse of dimnesionality
#only the best features to be kept
df.nunique()

Suburb             351
Address          34009
Rooms               12
Type                 3
Price             2871
Method               9
SellerG            388
Date                78
Distance           215
Postcode           211
Bedroom2            15
Bathroom            11
Car                 15
Landsize          1684
BuildingArea       740
YearBuilt          160
CouncilArea         33
Lattitude        13402
Longtitude       14524
Regionname           8
Propertycount      342
dtype: int64

In [23]:
#we will remove the categorical columns which hsa more than 50 unique values

In [33]:
for col in cat_col:
  if df[col].nunique()>50:
    df=df.drop(col,axis=1)

In [34]:
df.shape

(34857, 17)

In [35]:
df.nunique()

Rooms               12
Type                 3
Price             2871
Method               9
Distance           215
Postcode           211
Bedroom2            15
Bathroom            11
Car                 15
Landsize          1684
BuildingArea       740
YearBuilt          160
CouncilArea         33
Lattitude        13402
Longtitude       14524
Regionname           8
Propertycount      342
dtype: int64

In [36]:
df.head()

Rooms Type      Price Method  Distance  Postcode  Bedroom2  Bathroom  Car  \
0      2    h        NaN     SS       2.5    3067.0       2.0       1.0  1.0   
1      2    h  1480000.0      S       2.5    3067.0       2.0       1.0  1.0   
2      2    h  1035000.0      S       2.5    3067.0       2.0       1.0  0.0   
3      3    u        NaN     VB       2.5    3067.0       3.0       2.0  1.0   
4      3    h  1465000.0     SP       2.5    3067.0       3.0       2.0  0.0   

   Landsize  BuildingArea  YearBuilt         CouncilArea  Lattitude  \
0     126.0           NaN        NaN  Yarra City Council   -37.8014   
1     202.0           NaN        NaN  Yarra City Council   -37.7996   
2     156.0          79.0     1900.0  Yarra City Council   -37.8079   
3       0.0           NaN        NaN  Yarra City Council   -37.8114   
4     134.0         150.0     1900.0  Yarra City Council   -37.8093   

   Longtitude             Regionname  Propertycount  
0    144.9958  Northern Metropolitan         4019.0  
1    144.9984  Northern Metropolitan         4019.0  
2    144.9934  Northern Metropolitan         4019.0  
3    145.0116  Northern Metropolitan         4019.0  
4    144.9944  Northern Metropolitan         4019.0

In [37]:
df[['Rooms','Bedroom2']]

Rooms  Bedroom2
0          2       2.0
1          2       2.0
2          2       2.0
3          3       3.0
4          3       3.0
...      ...       ...
34852      4       4.0
34853      2       2.0
34854      2       2.0
34855      3       NaN
34856      2       2.0

[34857 rows x 2 columns]

In [38]:
df=df.drop(columns=['Bedroom2','Postcode','Lattitude','Longtitude'])
df.shape

(34857, 13)

In [39]:
df.head()

Rooms Type      Price Method  Distance  Bathroom  Car  Landsize  \
0      2    h        NaN     SS       2.5       1.0  1.0     126.0   
1      2    h  1480000.0      S       2.5       1.0  1.0     202.0   
2      2    h  1035000.0      S       2.5       1.0  0.0     156.0   
3      3    u        NaN     VB       2.5       2.0  1.0       0.0   
4      3    h  1465000.0     SP       2.5       2.0  0.0     134.0   

   BuildingArea  YearBuilt         CouncilArea             Regionname  \
0           NaN        NaN  Yarra City Council  Northern Metropolitan   
1           NaN        NaN  Yarra City Council  Northern Metropolitan   
2          79.0     1900.0  Yarra City Council  Northern Metropolitan   
3           NaN        NaN  Yarra City Council  Northern Metropolitan   
4         150.0     1900.0  Yarra City Council  Northern Metropolitan   

   Propertycount  
0         4019.0  
1         4019.0  
2         4019.0  
3         4019.0  
4         4019.0

In [40]:
df.isnull().sum()

Rooms                0
Type                 0
Price             7610
Method               0
Distance             1
Bathroom          8226
Car               8728
Landsize         11810
BuildingArea     21115
YearBuilt        19306
CouncilArea          3
Regionname           3
Propertycount        3
dtype: int64

In [43]:
df['Landsize']=df['Landsize'].fillna(df['Landsize'].mean())
df['BuildingArea']=df['BuildingArea'].fillna(df['BuildingArea'].mean())

In [70]:
df['Landsize'].mean()

593.5989933612818

In [69]:
df['Propertycount'].mode().values[0]

21650.0

In [72]:
df['Propertycount']=df['Propertycount'].fillna(df['Propertycount'].mode().values[0])
df['Bathroom']=df['Bathroom'].fillna(df['Bathroom'].mode().values[0])
df['Car']=df['Car'].fillna(df['Car'].mode().values[0])
df['Distance']=df['Distance'].fillna(df['Distance'].mode().values[0])

In [66]:
df.isnull().sum()

Rooms                0
Type                 0
Price             7610
Method               0
Distance             0
Bathroom             0
Car                  0
Landsize             0
BuildingArea         0
YearBuilt        19306
CouncilArea          3
Regionname           3
Propertycount        0
dtype: int64

In [74]:
df[['YearBuilt']]

YearBuilt
0            NaN
1            NaN
2         1900.0
3            NaN
4         1900.0
...          ...
34852        NaN
34853     2018.0
34854     2000.0
34855        NaN
34856     1930.0

[34857 rows x 1 columns]

In [75]:
df['YearBuilt']=2021-df['YearBuilt']


In [77]:
df['YearBuilt']=df['YearBuilt'].fillna(df['YearBuilt'].mode().values[0])

In [78]:
df[['YearBuilt']]

YearBuilt
0           51.0
1           51.0
2          121.0
3           51.0
4          121.0
...          ...
34852       51.0
34853        3.0
34854       21.0
34855       51.0
34856       91.0

[34857 rows x 1 columns]

In [80]:
df['Price']=df['Price'].fillna(df['Price'].mean())

In [82]:
df=df.dropna()
df

Rooms Type         Price Method  Distance  Bathroom  Car    Landsize  \
0          2    h  1.050173e+06     SS       2.5       1.0  1.0  126.000000   
1          2    h  1.480000e+06      S       2.5       1.0  1.0  202.000000   
2          2    h  1.035000e+06      S       2.5       1.0  0.0  156.000000   
3          3    u  1.050173e+06     VB       2.5       2.0  1.0    0.000000   
4          3    h  1.465000e+06     SP       2.5       2.0  0.0  134.000000   
...      ...  ...           ...    ...       ...       ...  ...         ...   
34852      4    h  1.480000e+06     PI       6.3       1.0  3.0  593.000000   
34853      2    h  8.880000e+05     SP       6.3       2.0  1.0   98.000000   
34854      2    t  7.050000e+05      S       6.3       1.0  2.0  220.000000   
34855      3    h  1.140000e+06     SP       6.3       1.0  2.0  593.598993   
34856      2    h  1.020000e+06     PI       6.3       1.0  0.0  250.000000   

       BuildingArea  YearBuilt               CouncilArea  \
0          160.2564       51.0        Yarra City Council   
1          160.2564       51.0        Yarra City Council   
2           79.0000      121.0        Yarra City Council   
3          160.2564       51.0        Yarra City Council   
4          150.0000      121.0        Yarra City Council   
...             ...        ...                       ...   
34852      160.2564       51.0  Maribyrnong City Council   
34853      104.0000        3.0  Maribyrnong City Council   
34854      120.0000       21.0  Maribyrnong City Council   
34855      160.2564       51.0  Maribyrnong City Council   
34856      103.0000       91.0  Maribyrnong City Council   

                  Regionname  Propertycount  
0      Northern Metropolitan         4019.0  
1      Northern Metropolitan         4019.0  
2      Northern Metropolitan         4019.0  
3      Northern Metropolitan         4019.0  
4      Northern Metropolitan         4019.0  
...                      ...            ...  
34852   Western Metropolitan         6543.0  
34853   Western Metropolitan         6543.0  
34854   Western Metropolitan         6543.0  
34855   Western Metropolitan         6543.0  
34856   Western Metropolitan         6543.0  

[34854 rows x 13 columns]

In [83]:
df.isnull().sum()

Rooms            0
Type             0
Price            0
Method           0
Distance         0
Bathroom         0
Car              0
Landsize         0
BuildingArea     0
YearBuilt        0
CouncilArea      0
Regionname       0
Propertycount    0
dtype: int64

In [84]:
df2=df.copy().select_dtypes(exclude='object')
df2

Rooms         Price  Distance  Bathroom  Car    Landsize  BuildingArea  \
0          2  1.050173e+06       2.5       1.0  1.0  126.000000      160.2564   
1          2  1.480000e+06       2.5       1.0  1.0  202.000000      160.2564   
2          2  1.035000e+06       2.5       1.0  0.0  156.000000       79.0000   
3          3  1.050173e+06       2.5       2.0  1.0    0.000000      160.2564   
4          3  1.465000e+06       2.5       2.0  0.0  134.000000      150.0000   
...      ...           ...       ...       ...  ...         ...           ...   
34852      4  1.480000e+06       6.3       1.0  3.0  593.000000      160.2564   
34853      2  8.880000e+05       6.3       2.0  1.0   98.000000      104.0000   
34854      2  7.050000e+05       6.3       1.0  2.0  220.000000      120.0000   
34855      3  1.140000e+06       6.3       1.0  2.0  593.598993      160.2564   
34856      2  1.020000e+06       6.3       1.0  0.0  250.000000      103.0000   

       YearBuilt  Propertycount  
0           51.0         4019.0  
1           51.0         4019.0  
2          121.0         4019.0  
3           51.0         4019.0  
4          121.0         4019.0  
...          ...            ...  
34852       51.0         6543.0  
34853        3.0         6543.0  
34854       21.0         6543.0  
34855       51.0         6543.0  
34856       91.0         6543.0  

[34854 rows x 9 columns]

In [88]:
x=df2.drop('Price',axis=1).values
y=df2['Price'].values

In [91]:
y

array([1050173.34495541, 1480000.        , 1035000.        , ...,
        705000.        , 1140000.        , 1020000.        ])

In [92]:
from sklearn.model_selection import train_test_split as split

In [93]:
x_train,x_test,y_train,y_test=split(x,y,random_state=2)

In [94]:
x.shape

(34854, 8)

In [96]:
x_train.shape

(26140, 8)

In [97]:
x_test.shape

(8714, 8)

In [99]:
26140/34854

0.7499856544442531

In [100]:
from sklearn.linear_model import LinearRegression as LR
model=LR()

In [101]:
model.fit(x_train,y_train)

LinearRegression()

In [102]:
y_pred=model.predict(x_test)
y_pred

array([ 912027.78380951, 1005031.34239193, 1227938.15197248, ...,
        507024.71652679, 1015759.32522718,  925226.61718462])

In [103]:
y_test

array([ 820000.        ,  680000.        , 1388000.        , ...,
        760000.        , 1050173.34495541,  445000.        ])

In [108]:
df2.head(0)

Empty DataFrame
Columns: [Rooms, Price, Distance, Bathroom, Car, Landsize, BuildingArea, YearBuilt, Propertycount]
Index: []

In [104]:
x_test[0]

array([  2.        ,   5.9       ,   1.        ,   2.        ,
       593.59899336, 160.25640036,  51.        , 394.        ])

In [109]:
a=np.array([[1,4.2,1,1,400,150,20,500]])

In [110]:
model.predict(a)

array([595510.22976693])

In [111]:
from sklearn.metrics import mean_squared_error, r2_score

In [112]:
mean_squared_error(y_pred,y_test)

207464398564.0018

In [114]:
r2_score(y_test,y_pred)

0.3158892845482729